"""python tools/hardware_report.py  -> results/hardware_report.json + docs/HARDWARE_REPORT.md  (mass, power/battery, thermal duty, actuator trade)."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dataclasses import replace
from hardware.mass_budget import mass_budget, avg_power_w, battery_for, time_to_derate_s, ACTUATED_30
from actuators.joint_actuator import PH54_200, PH54_100, MX106, spec_for_joint
from tools.actuator_tradeoff import evaluate

def main():
    req = json.load(open("results/fullbody/motor_requirements.json"))
    mb = mass_budget()
    # variant: lighter arms (all arm joints MX-106-class) to see what it takes to make 25 kg work
    light = lambda n: MX106 if any(k in n for k in ("sh_", "elbow", "wr_", "neck")) else spec_for_joint(n)
    mb_light = mass_budget(spec_fn=light)
    P = avg_power_w(); bats = {m: battery_for(P, m) for m in (15, 30, 60)}
    thermal = [dict(com_height_m=r["com_height_m"], knee_nm=r["knee_Nm"], t_to_derate_s=time_to_derate_s(PH54_200, r["knee_Nm"])) for r in req]
    rep = dict(mass_budget=mb, mass_budget_light_arms=mb_light, walking_avg_power_w=P, battery=bats, knee_thermal=thermal, actuator_tradeoff=evaluate(req))
    os.makedirs("results", exist_ok=True); json.dump(rep, open("results/hardware_report.json", "w"), indent=1)
    L = ["# Hardware report (generated by tools/hardware_report.py)", "",
         "All thermal/power inputs marked ASSUMED in code; treat as planning numbers until measured.", "",
         "## Mass", f"- Simulated robot: **{mb['model_mass_kg']:.1f} kg**; {mb['n_actuators']} actuators (datasheet masses) = **{mb['actuators_kg']:.1f} kg**, electronics {mb['electronics_kg']} kg, grippers {mb['grippers_kg']} kg",
         f"- Left for structure + battery: **{mb['left_for_structure_kg']:.1f} kg** -> {'OK' if mb['feasible'] else '**NOT FEASIBLE** (structure alone usually needs 20-35 % of the mass)'}",
         f"- With MX-106-class arms/neck: actuators {mb_light['actuators_kg']:.1f} kg, left {mb_light['left_for_structure_kg']:.1f} kg -> {'OK' if mb_light['feasible'] else 'still not feasible'}", "",
         "## Power / battery (walking average, ASSUMED torque fractions)", f"- Average electrical power ~ **{P:.0f} W**"] + \
        [f"- {m} min runtime: {b['energy_wh']:.0f} Wh, ~{b['mass_kg']:.1f} kg pack" for m, b in bats.items()] + ["", "## Knee thermal (PH54-200, time at the measured gait torque before fold-back starts)"] + \
        [f"- CoM {t['com_height_m']:.2f} m: knee {t['knee_nm']:.1f} Nm -> " + ("never (steady state below derate)" if t['t_to_derate_s'] == float('inf') else f"{t['t_to_derate_s']/60:.1f} min") for t in thermal]
    open("docs/HARDWARE_REPORT.md", "w").write("\n".join(L) + "\n"); print("\n".join(L))

if __name__ == "__main__": main()
